[package]
name = "anyxplorer"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
anyxplore = { path = "lib" }
png = "0.17.16"

bnl = { path = "../ghoulies_reader" }
fltk = "1.5.13"
eframe = "0.32.1"
egui_ltreeview = "0.5.3"
