[package]
name = "anyxplorer"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
anyxplore = { path = "lib" }
png = "0.17.16"

bnl = { git = "https://github.com/luboise/bnl.git" }
fltk = "1.5.13"
